import { ArtistProducts } from "../assests/Images";
export const IMAGES = [
  ArtistProducts.BADGE,
  ArtistProducts.BLACK_HOODIE,
  ArtistProducts.WHITE_HOODIE,
  ArtistProducts.TSHIRT_BLACK,
  ArtistProducts.TSHIRT,
  ArtistProducts.BOOK_MART,
  ArtistProducts.CUSHIONS,
  ArtistProducts.ENVELOPS,
  ArtistProducts.FRAME,
  ArtistProducts.GOODY_BAG,
  ArtistProducts.GREETING_CARD,
  ArtistProducts.GYM_BOOTLE,
  ArtistProducts.KEY_CHAIN,
  ArtistProducts.MUG,
  ArtistProducts.NOTEBOOK,
  ArtistProducts.PHONE_CASE,
  ArtistProducts.STICKER,
  ArtistProducts.TAG,
  ArtistProducts.TEA_COASTER_ROUND,
  ArtistProducts.TEA_COASTER_SQUARE,
  ArtistProducts.TOTE_BAG,
];

export const BOUNDS = [
  {
    borderRadius: "100px",
    marginTop: "170px",
    marginLeft: "85px",
    width: "200px",
    height: "200px",
    position: "absolute",
    overflow: "hidden",
  },
  {
    marginTop: "190px",
    marginLeft: "188px",
    width: "105px",
    height: "120px",
    position: "absolute",
    overflow: "hidden",
  },
  {
    marginTop: "190px",
    marginLeft: "188px",
    width: "105px",
    height: "120px",
    position: "absolute",
    overflow: "hidden",
  },
  {
    marginTop: "118px",
    marginLeft: "188px",
    width: "120px",
    height: "143px",
    position: "absolute",
  },
  {
    marginTop: "90px",
    marginLeft: "205px",
    width: "115px",
    height: "330px",
    position: "absolute",
  },
  {
    marginTop: "138px",
    marginLeft: "145px",
    width: "215px",
    height: "210px",
    position: "absolute",
  },
  {
    marginTop: "165px",
    marginLeft: "96px",
    width: "300px",
    height: "155px",
    position: "absolute",
  },
  {
    marginTop: "100px",
    marginLeft: "146px",
    width: "215px",
    height: "300px",
    position: "absolute",
  },
  {
    marginTop: "175px",
    marginLeft: "146px",
    width: "200px",
    height: "230px",
    position: "absolute",
  },
  {
    marginTop: "115px",
    marginLeft: "170px",
    width: "180px",
    height: "300px",
    position: "absolute",
  },
  {
    marginTop: "200px",
    marginLeft: "200px",
    width: "100px",
    height: "170px",
    position: "absolute",
  },
  {
    marginTop: "180px",
    marginLeft: "198px",
    width: "110px",
    height: "250px",
    position: "absolute",
  },
  {
    marginTop: "120px",
    marginLeft: "120px",
    width: "215px",
    height: "260px",
    position: "absolute",
  },
  {
    marginTop: "60px",
    marginLeft: "120px",
    width: "265px",
    height: "380px",
    position: "absolute",
  },
  {
    marginTop: "70px",
    marginLeft: "160px",
    width: "173px",
    height: "340px",
    position: "absolute",
  },
  {
    borderRadius: "160px",
    marginTop: "105px",
    marginLeft: "105px",
    width: "290px",
    height: "290px",
    position: "absolute",
  },
  {
    marginTop: "200px",
    marginLeft: "200px",
    width: "100px",
    height: "180px",
    position: "absolute",
  },
  {
    borderRadius: "160px",
    marginTop: "105px",
    marginLeft: "105px",
    width: "290px",
    height: "290px",
    position: "absolute",
  },
  {
    marginTop: "120px",
    marginLeft: "120px",
    width: "260px",
    height: "260px",
    position: "absolute",
  },
  {
    marginTop: "235px",
    marginLeft: "180px",
    width: "150px",
    height: "170px",
    position: "absolute",
  },
];

const IMAGES_LIST = [
  {
    imgName: "badge",
    Image: 0,
    uniques: 0,
    position: { x: -150, y: -145 },
    horizontal: { x: -150, y: -145 },
    vertical: { x: -152, y: -145 },
    sliderValue: 8,
    boundImage: [0],
    disable: true,
    bounds: 0,
    EditedSetting: "",
    EditedImage: "",
  },
  {
    imgName: "blackHood",
    Image: 1,
    uniques: 1,
    position: { x: -195, y: -185 },
    horizontal: { x: -195, y: -185 },
    vertical: { x: -196, y: -190 },
    sliderValue: 8,
    disable: false,
    bounds: 1,
    boundImage: [1],
    EditedSetting: "",
    EditedImage: "",
  },
  {
    imgName: "whiteHood",
    Image: 2,
    uniques: 2,
    position: { x: -187, y: -191 },
    horizontal: { x: -187, y: -191 },
    vertical: { x: -187, y: -191 },
    sliderValue: 8,
    disable: false,
    bounds: 2,
    boundImage: [2],
    EditedSetting: "",
    EditedImage: "",
  },
  {
    imgName: "Shirt",
    Image: 3,
    uniques: 3,
    position: { x: -183, y: -191 },
    horizontal: { x: -183, y: -191 },
    vertical: { x: -189, y: -182 },
    sliderValue: 8,
    disable: false,
    bounds: 3,

    boundImage: [3, 4],
    ListImage: ["Black", "White"],
  },
  {
    imgName: "Bookmark",
    Image: 5,
    uniques: 4,
    position: { x: -194, y: -82 },
    horizontal: { x: -194, y: -82 },
    vertical: { x: -194, y: -82 },
    sliderValue: 8,
    boundImage: [5],
    disable: false,
    bounds: 4,
  },
  {
    imgName: "Cusions",
    Image: 6,
    uniques: 5,
    position: { x: -144, y: -143 },
    horizontal: { x: -144, y: -143 },
    vertical: { x: -144, y: -143 },
    sliderValue: 8,
    boundImage: [6],
    disable: false,
    bounds: 5,
  },
  {
    imgName: "Env",
    Image: 7,
    uniques: 6,
    position: { x: -102, y: -176 },
    horizontal: { x: -102, y: -176 },
    vertical: { x: -102, y: -176 },
    sliderValue: 8,
    boundImage: [7],
    disable: false,
    bounds: 6,
  },
  {
    imgName: "Frame",
    Image: 8,
    uniques: 7,
    position: { x: -146, y: -103 },
    horizontal: { x: -146, y: -103 },
    vertical: { x: -146, y: -103 },
    sliderValue: 8,
    boundImage: [8],
    disable: false,
    bounds: 7,
  },
  {
    imgName: "bag",
    Image: 9,
    uniques: 8,
    position: { x: -149, y: -137 },
    horizontal: { x: -149, y: -137 },
    vertical: { x: -149, y: -137 },
    sliderValue: 8,
    boundImage: [9],
    disable: false,
    bounds: 8,
  },
  {
    imgName: "GREETING_CARD",
    Image: 10,
    uniques: 9,
    position: { x: -159, y: -97 },
    horizontal: { x: -159, y: -97 },
    vertical: { x: -159, y: -97 },
    sliderValue: 8,
    boundImage: [10],
    disable: false,
    bounds: 9,
  },
  {
    imgName: "bottle",
    Image: 11,
    uniques: 10,
    position: { x: -206, y: -168 },
    horizontal: { x: -206, y: -168 },
    vertical: { x: -206, y: -168 },
    sliderValue: 8,
    boundImage: [11],
    disable: false,
    bounds: 10,
  },
  {
    imgName: "keychain",
    Image: 12,
    uniques: 11,
    position: { x: -196, y: -122 },
    horizontal: { x: -196, y: -122 },
    vertical: { x: -196, y: -122 },
    sliderValue: 8,
    boundImage: [12],
    disable: false,
    bounds: 11,
  },
  {
    imgName: "mug",
    Image: 13,
    uniques: 12,
    position: { x: -144, y: -123 },
    horizontal: { x: -144, y: -123 },
    vertical: { x: -144, y: -123 },
    sliderValue: 8,
    boundImage: [13],
    disable: false,
    bounds: 12,
  },
  {
    imgName: "book",
    Image: 14,
    uniques: 13,
    position: { x: -120, y: -58 },
    horizontal: { x: -120, y: -58 },
    vertical: { x: -120, y: -58 },
    sliderValue: 8,
    boundImage: [14],
    disable: false,
    bounds: 13,
  },
  {
    imgName: "phonecase",
    Image: 15,
    uniques: 14,
    position: { x: -165, y: -73 },
    horizontal: { x: -165, y: -73 },
    vertical: { x: -165, y: -73 },
    sliderValue: 8,
    boundImage: [15],
    disable: false,
    bounds: 14,
  },
  {
    imgName: "Sticker",
    Image: 16,
    uniques: 15,
    position: { x: -110, y: -108 },
    horizontal: { x: -110, y: -108 },
    vertical: { x: -110, y: -108 },
    sliderValue: 8,
    boundImage: [16],
    disable: false,
    bounds: 15,
  },
  {
    imgName: "tag",
    Image: 17,
    uniques: 16,
    position: { x: -203, y: -158 },
    horizontal: { x: -203, y: -158 },
    vertical: { x: -203, y: -158 },
    sliderValue: 8,
    boundImage: [17],
    disable: false,
    bounds: 16,
  },
  {
    imgName: "TeaRound",
    Image: 18,
    uniques: 17,
    position: { x: -108, y: -101 },
    horizontal: { x: -108, y: -101 },
    vertical: { x: -108, y: -101 },
    sliderValue: 8,
    boundImage: [18],
    disable: false,
    bounds: 17,
  },
  {
    imgName: "TeaSquare",
    Image: 19,
    uniques: 18,
    position: { x: -122, y: -122 },
    horizontal: { x: -122, y: -122 },
    vertical: { x: -122, y: -122 },
    sliderValue: 8,
    boundImage: [19],
    disable: false,
    bounds: 18,
  },
  {
    imgName: "Tote",
    Image: 20,
    uniques: 19,
    position: { x: -177, y: -164 },
    horizontal: { x: -177, y: -164 },
    vertical: { x: -177, y: -164 },
    sliderValue: 8,
    boundImage: [20],
    disable: false,
    bounds: 19,
  },
];

export const ProductList = (file) => {
  IMAGES_LIST.forEach((product) => {
    product.ImageHover = file;
  });
  const chunkedCards = [];
  for (let i = 0; i < IMAGES_LIST.length; i += 3) {
    chunkedCards.push(IMAGES_LIST.slice(i, i + 3));
  }
  return chunkedCards;
};
